Read unathenticated

diff --git a/.github/workflows/php.yml b/.github/workflows/php.yml
--- a/.github/workflows/php.yml
+++ b/.github/workflows/php.yml
@@ -48,19 +48,19 @@ jobs:
           ../vendor/bin/drush pm:enable devel devel_generate
           ../vendor/bin/drush devel-generate:content 10 --bundles=article
           ../vendor/bin/drush devel-generate:content 10 --bundles=page
-          php -S localhost:8099 .ht.router.php 2> /dev/null &
+          php -S 127.0.0.1:8099 .ht.router.php 2> /dev/null &
 
       - name: Scan Site
         run: |
           cd web
           # First scan as anonymous.
-          php ../scripts/spider.php > sites/default/files/map-source.xml
-          cat sites/default/files/map-source.xml
-          ../node_modules/.bin/pa11y-ci --sitemap http://localhost:8099/sites/default/files/map-source.xml || echo "Errors Found!"
+          php ../scripts/spider.php > map-source.xml
+          cat map-source.xml
+          ../node_modules/.bin/pa11y-ci --sitemap http://127.0.0.1:8099/map-source.xml || echo "Errors Found!"
           # Then scan as user 1.
-          head -n 2 sites/default/files/map-source.xml > sites/default/files/map.xml
-          printf "  <url><loc>%s</url></loc>\n" "$(../vendor/bin/drush --uri=http://localhost:8099/ --no-browser uli /)" >> sites/default/files/map.xml
-          grep '^ ' sites/default/files/map-source.xml >> sites/default/files/map.xml
-          echo '</urlset>' >> sites/default/files/map.xml
-          cat sites/default/files/map.xml
-          ../node_modules/.bin/pa11y-ci --sitemap http://localhost:8099/sites/default/files/map.xml || echo "Errors Found!"
+          head -n 2 map-source.xml > map.xml
+          printf "  <url><loc>%s</url></loc>\n" "$(../vendor/bin/drush --uri=http://127.0.0.1:8099/ --no-browser uli /)" >> map.xml
+          grep '^ ' map-source.xml >> map.xml
+          echo '</urlset>' >> map.xml
+          cat map.xml
+          ../node_modules/.bin/pa11y-ci --sitemap http://127.0.0.1:8099/map.xml || echo "Errors Found!"
