Read unathenticated

diff --git a/.github/workflows/php.yml b/.github/workflows/php.yml
--- a/.github/workflows/php.yml
+++ b/.github/workflows/php.yml
@@ -48,19 +48,21 @@ jobs:
           ../vendor/bin/drush pm:enable devel devel_generate
           ../vendor/bin/drush devel-generate:content 10 --bundles=article
           ../vendor/bin/drush devel-generate:content 10 --bundles=page
-          php -S localhost:8099 .ht.router.php 2>&1 > /dev/null &
-          php ../scripts/spider.php > sites/default/files/map-source.xml
 
       - name: Scan Site as Anonymous
         run: |
-          php scripts/spider.php > web/map-source.xml
-          node_modules/.bin/pa11y-ci --sitemap http://localhost:8099/sites/default/files/map-source.xml || echo "Errors Found!"
+          cd web
+          php -S localhost:8099 .ht.router.php 2>&1 > /dev/null &
+          php ../scripts/spider.php > map-source.xml
+          ../node_modules/.bin/pa11y-ci --sitemap http://localhost:8099/map-source.xml || echo "Errors Found!"
 
       - name: Scan Site as Admin
         run: |
-          head -n 1 web/sites/default/files/map-source.xml > web/sites/default/files/map.xml
-          printf "<url><loc>%s</url></loc>\n" "$(vendor/bin/drush --uri=http://localhost:8099/ --no-browser uli /)" >> web/sites/default/files/map.xml
-          grep '^ ' web/sites/default/files/map-source.xml >> web/sites/default/files/map.xml
-          echo '</urlset>' >> web/sites/default/files/map.xml
-          cat web/sites/default/files/map.xml
-          node_modules/.bin/pa11y-ci --sitemap http://localhost:8099/sites/default/files/map.xml || echo "Errors Found!"
+          cd web
+          php -S localhost:8099 .ht.router.php 2>&1 > /dev/null &
+          head -n 1 map-source.xml > map.xml
+          printf "<url><loc>%s</url></loc>\n" "$(../vendor/bin/drush --uri=http://localhost:8099/ --no-browser uli /)" >> map.xml
+          grep '^ ' map-source.xml >> map.xml
+          echo '</urlset>' >> map.xml
+          cat map.xml
+          ../node_modules/.bin/pa11y-ci --sitemap http://localhost:8099/map.xml || echo "Errors Found!"
