Read unathenticated

diff --git a/.github/workflows/php.yml b/.github/workflows/php.yml
--- a/.github/workflows/php.yml
+++ b/.github/workflows/php.yml
@@ -53,17 +53,17 @@ jobs:
       - name: Scan Site as Anonymous
         run: |
           cd web
-          php -S localhost:8099 .ht.router.php &
-          ../node_modules/.bin/pa11y-ci -c ../.pa11yci
+          php -S localhost:8099 .ht.router.php > /dev/null &
+          ../node_modules/.bin/pa11y-ci -c ../.pa11yci || echo "Errors Found!"
 
       - name: Scan Site as Admin
         run: |
           cd web
-          php -S localhost:8099 .ht.router.php &
+          php -S localhost:8099 .ht.router.php > /dev/null &
           curl http://localhost:8099/sitemap.xml | head -n 3 > map.xml
           printf '<url><loc>' >> map.xml
           ../vendor/bin/drush --uri=http://localhost:8099/ --no-browser uli / >>  map.xml
           echo '</url></loc>' >> map.xml
           curl http://localhost:8099/sitemap.xml |grep '^<url><loc>' >> map.xml
           echo '</urlset>' >> map.xml
-          ../node_modules/.bin/pa11y-ci -c ../.pa11yci --sitemap http://localhost:8099/map.xml
+          ../node_modules/.bin/pa11y-ci -c ../.pa11yci --sitemap http://localhost:8099/map.xml || echo "Errors Found!"
