Read unathenticated

diff --git a/.github/workflows/php.yml b/.github/workflows/php.yml
--- a/.github/workflows/php.yml
+++ b/.github/workflows/php.yml
@@ -24,17 +24,18 @@ jobs:
       - name: Validate composer.json and composer.lock
         run: composer validate
 
-      - name: Cache Composer packages
-        id: composer-cache
-        uses: actions/cache@v2
-        with:
-          path: vendor
-          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
+#      - name: Cache Composer packages
+#        id: composer-cache
+#        uses: actions/cache@v2
+#        with:
+#          path: vendor
+#          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
+#          restore-keys: |
+#            ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
+#
 
       - name: Install dependencies
-        if: steps.composer-cache.outputs.cache-hit != 'true'
+#        if: steps.composer-cache.outputs.cache-hit != 'true'
         run: composer install --ignore-platform-reqs --prefer-dist --no-progress --no-suggest
 
       - name: Install node
@@ -52,17 +53,14 @@ jobs:
 
       - name: Scan Site as Anonymous
         run: |
-          cd web
-          ../node_modules/.bin/pa11y-ci -c ../.pa11yci --sitemap http://localhost:8099/map-source.xml || echo "Errors Found!"
+          php scripts/spider.php > web/map-source.xml
+          node_modules/.bin/pa11y-ci --sitemap http://localhost:8099/map-source.xml || echo "Errors Found!"
 
       - name: Scan Site as Admin
         run: |
-          cd web
-          curl -s http://localhost:8099/sitemap.xml > map-source.xml
-          head -n 1 map-source.xml > map.xml
-          printf "<url><loc>%s</url></loc>\n" "$(../vendor/bin/drush --uri=http://localhost:8099/ --no-browser uli /)" >> map.xml
-          grep '^ ' map-source.xml >> map.xml
-          echo '</urlset>' >> map.xml
-          cat map.xml
-          php -S localhost:8099 .ht.router.php 2>&1 > /dev/null &
-          ../node_modules/.bin/pa11y-ci -c ../.pa11yci --sitemap http://localhost:8099/map.xml || echo "Errors Found!"
+          head -n 1 web/map-source.xml > web/map.xml
+          printf "<url><loc>%s</url></loc>\n" "$(../vendor/bin/drush --uri=http://localhost:8099/ --no-browser uli /)" >> web/map.xml
+          grep '^ ' web/map-source.xml >> web/map.xml
+          echo '</urlset>' >> web/map.xml
+          cat web/map.xml
+          node_modules/.bin/pa11y-ci --sitemap http://localhost:8099/map.xml || echo "Errors Found!"
